# Generated by Django 3.1.6 on 2021-03-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcotentimagelink',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contenttype',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(blank='False', max_length=2500),
        ),
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='PostContentText',
        ),
        migrations.DeleteModel(
            name='PostCotentImageLink',
        ),
    ]
