# Generated by Django 3.1.6 on 2021-03-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('githublink', models.URLField()),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
