# Generated by Django 3.1.6 on 2021-04-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='../img/face.svg', upload_to='images/'),
        ),
    ]
