# Generated by Django 2.2.5 on 2021-03-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdist', '0002_auto_20210304_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='username',
            new_name='name',
        ),
    ]
