# Generated by Django 2.2.5 on 2021-03-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdist', '0003_auto_20210304_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenttype',
            field=models.CharField(choices=[('T', 'Text'), ('I', 'Image'), ('L', 'ImageLink'), ('C', 'CommonMark')], default='T', max_length=1),
        ),
    ]
