# Generated by Django 3.1.7 on 2021-03-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdist', '0004_auto_20210305_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
