# Generated by Django 2.2.5 on 2021-03-04 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialdist', '0004_post_contenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCotentImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdist.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostContentText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2500)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdist.Post')),
            ],
        ),
    ]
